import src.commands.battle
import src.commands.exit
import src.commands.heal
import src.commands.help
import src.commands.license
import src.commands.move
import src.commands.warranty
import src.commands.command_base
import src.commands.command_handler